// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: content.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSearchContents = `-- name: CountSearchContents :one
SELECT COUNT(*)
FROM contents
WHERE (
        $1::text = '' OR 
        to_tsvector('english', title) @@ plainto_tsquery('english', $1::text)
    )
    AND (
        cardinality($2::text[]) = 0 OR 
        tags && $2::text[]
    )
    AND (
        cardinality($3::text[]) = 0 OR 
        type = ANY($3::text[])
    )
`

type CountSearchContentsParams struct {
	Query        string   `json:"query"`
	Tags         []string `json:"tags"`
	ContentTypes []string `json:"content_types"`
}

func (q *Queries) CountSearchContents(ctx context.Context, arg CountSearchContentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchContents, arg.Query, arg.Tags, arg.ContentTypes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteContent = `-- name: DeleteContent :exec
DELETE FROM contents WHERE id = $1
`

func (q *Queries) DeleteContent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteContent, id)
	return err
}

const getContentByExternalID = `-- name: GetContentByExternalID :one
SELECT id, external_id, provider, title, type, published_at,
       views, likes, reactions, reading_time, score, tags, created_at, updated_at
FROM contents
WHERE provider = $1 AND external_id = $2
`

type GetContentByExternalIDParams struct {
	Provider   string `json:"provider"`
	ExternalID string `json:"external_id"`
}

type GetContentByExternalIDRow struct {
	ID          pgtype.UUID      `json:"id"`
	ExternalID  string           `json:"external_id"`
	Provider    string           `json:"provider"`
	Title       string           `json:"title"`
	Type        string           `json:"type"`
	PublishedAt pgtype.Timestamp `json:"published_at"`
	Views       pgtype.Int4      `json:"views"`
	Likes       pgtype.Int4      `json:"likes"`
	Reactions   pgtype.Int4      `json:"reactions"`
	ReadingTime pgtype.Int4      `json:"reading_time"`
	Score       pgtype.Numeric   `json:"score"`
	Tags        []string         `json:"tags"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetContentByExternalID(ctx context.Context, arg GetContentByExternalIDParams) (GetContentByExternalIDRow, error) {
	row := q.db.QueryRow(ctx, getContentByExternalID, arg.Provider, arg.ExternalID)
	var i GetContentByExternalIDRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Provider,
		&i.Title,
		&i.Type,
		&i.PublishedAt,
		&i.Views,
		&i.Likes,
		&i.Reactions,
		&i.ReadingTime,
		&i.Score,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContentByID = `-- name: GetContentByID :one
SELECT id, external_id, provider, title, type, published_at,
       views, likes, reactions, reading_time, score, tags, created_at, updated_at
FROM contents
WHERE id = $1
`

type GetContentByIDRow struct {
	ID          pgtype.UUID      `json:"id"`
	ExternalID  string           `json:"external_id"`
	Provider    string           `json:"provider"`
	Title       string           `json:"title"`
	Type        string           `json:"type"`
	PublishedAt pgtype.Timestamp `json:"published_at"`
	Views       pgtype.Int4      `json:"views"`
	Likes       pgtype.Int4      `json:"likes"`
	Reactions   pgtype.Int4      `json:"reactions"`
	ReadingTime pgtype.Int4      `json:"reading_time"`
	Score       pgtype.Numeric   `json:"score"`
	Tags        []string         `json:"tags"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetContentByID(ctx context.Context, id pgtype.UUID) (GetContentByIDRow, error) {
	row := q.db.QueryRow(ctx, getContentByID, id)
	var i GetContentByIDRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Provider,
		&i.Title,
		&i.Type,
		&i.PublishedAt,
		&i.Views,
		&i.Likes,
		&i.Reactions,
		&i.ReadingTime,
		&i.Score,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchContents = `-- name: SearchContents :many
SELECT id, external_id, provider, title, type, published_at,
       views, likes, reactions, reading_time, score, tags, created_at, updated_at
FROM contents
WHERE (
        $1::text = '' OR 
        to_tsvector('english', title) @@ plainto_tsquery('english', $1::text)
    )
    AND (
        cardinality($2::text[]) = 0 OR 
        tags && $2::text[]
    )
    AND (
        cardinality($3::text[]) = 0 OR 
        type = ANY($3::text[])
    )
ORDER BY
    CASE WHEN $4::varchar = 'popularity' THEN (views + likes + reactions) END DESC,
    score DESC
LIMIT $6::int OFFSET $5::int
`

type SearchContentsParams struct {
	Query        string   `json:"query"`
	Tags         []string `json:"tags"`
	ContentTypes []string `json:"content_types"`
	SortBy       string   `json:"sort_by"`
	PageOffset   int32    `json:"page_offset"`
	PageLimit    int32    `json:"page_limit"`
}

type SearchContentsRow struct {
	ID          pgtype.UUID      `json:"id"`
	ExternalID  string           `json:"external_id"`
	Provider    string           `json:"provider"`
	Title       string           `json:"title"`
	Type        string           `json:"type"`
	PublishedAt pgtype.Timestamp `json:"published_at"`
	Views       pgtype.Int4      `json:"views"`
	Likes       pgtype.Int4      `json:"likes"`
	Reactions   pgtype.Int4      `json:"reactions"`
	ReadingTime pgtype.Int4      `json:"reading_time"`
	Score       pgtype.Numeric   `json:"score"`
	Tags        []string         `json:"tags"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) SearchContents(ctx context.Context, arg SearchContentsParams) ([]SearchContentsRow, error) {
	rows, err := q.db.Query(ctx, searchContents,
		arg.Query,
		arg.Tags,
		arg.ContentTypes,
		arg.SortBy,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchContentsRow{}
	for rows.Next() {
		var i SearchContentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Provider,
			&i.Title,
			&i.Type,
			&i.PublishedAt,
			&i.Views,
			&i.Likes,
			&i.Reactions,
			&i.ReadingTime,
			&i.Score,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertContent = `-- name: UpsertContent :one
INSERT INTO contents (
    external_id, provider, title, type, published_at, raw_data,
    views, likes, reactions, reading_time, score, tags
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12
)
ON CONFLICT (provider, external_id)
DO UPDATE SET
    title = EXCLUDED.title,
    published_at = EXCLUDED.published_at,
    raw_data = EXCLUDED.raw_data,
    views = EXCLUDED.views,
    likes = EXCLUDED.likes,
    reactions = EXCLUDED.reactions,
    reading_time = EXCLUDED.reading_time,
    score = EXCLUDED.score,
    tags = EXCLUDED.tags,
    updated_at = NOW()
RETURNING id, created_at, updated_at
`

type UpsertContentParams struct {
	ExternalID  string           `json:"external_id"`
	Provider    string           `json:"provider"`
	Title       string           `json:"title"`
	Type        string           `json:"type"`
	PublishedAt pgtype.Timestamp `json:"published_at"`
	RawData     []byte           `json:"raw_data"`
	Views       pgtype.Int4      `json:"views"`
	Likes       pgtype.Int4      `json:"likes"`
	Reactions   pgtype.Int4      `json:"reactions"`
	ReadingTime pgtype.Int4      `json:"reading_time"`
	Score       pgtype.Numeric   `json:"score"`
	Tags        []string         `json:"tags"`
}

type UpsertContentRow struct {
	ID        pgtype.UUID      `json:"id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpsertContent(ctx context.Context, arg UpsertContentParams) (UpsertContentRow, error) {
	row := q.db.QueryRow(ctx, upsertContent,
		arg.ExternalID,
		arg.Provider,
		arg.Title,
		arg.Type,
		arg.PublishedAt,
		arg.RawData,
		arg.Views,
		arg.Likes,
		arg.Reactions,
		arg.ReadingTime,
		arg.Score,
		arg.Tags,
	)
	var i UpsertContentRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const searchContentsByProvider = `-- name: SearchContentsByProvider :many
SELECT id, external_id, provider, title, type, published_at,
       views, likes, reactions, reading_time, score, tags, created_at, updated_at
FROM contents
WHERE provider = $1::varchar
  AND (
    $2::text = '' OR
    to_tsvector('english', title) @@ plainto_tsquery('english', $2::text)
  )
ORDER BY score DESC
LIMIT $4::int OFFSET $3::int
`

type SearchContentsByProviderParams struct {
	Provider   string `json:"provider"`
	Query      string `json:"query"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

type SearchContentsByProviderRow struct {
	ID          pgtype.UUID      `json:"id"`
	ExternalID  string           `json:"external_id"`
	Provider    string           `json:"provider"`
	Title       string           `json:"title"`
	Type        string           `json:"type"`
	PublishedAt pgtype.Timestamp `json:"published_at"`
	Views       pgtype.Int4      `json:"views"`
	Likes       pgtype.Int4      `json:"likes"`
	Reactions   pgtype.Int4      `json:"reactions"`
	ReadingTime pgtype.Int4      `json:"reading_time"`
	Score       pgtype.Numeric   `json:"score"`
	Tags        []string         `json:"tags"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) SearchContentsByProvider(ctx context.Context, arg SearchContentsByProviderParams) ([]SearchContentsByProviderRow, error) {
	rows, err := q.db.Query(ctx, searchContentsByProvider,
		arg.Provider,
		arg.Query,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchContentsByProviderRow{}
	for rows.Next() {
		var i SearchContentsByProviderRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Provider,
			&i.Title,
			&i.Type,
			&i.PublishedAt,
			&i.Views,
			&i.Likes,
			&i.Reactions,
			&i.ReadingTime,
			&i.Score,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
