// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Content struct {
	ID          pgtype.UUID      `json:"id"`
	ExternalID  string           `json:"external_id"`
	Provider    string           `json:"provider"`
	Title       string           `json:"title"`
	Type        string           `json:"type"`
	PublishedAt pgtype.Timestamp `json:"published_at"`
	RawData     []byte           `json:"raw_data"`
	Views       pgtype.Int4      `json:"views"`
	Likes       pgtype.Int4      `json:"likes"`
	Reactions   pgtype.Int4      `json:"reactions"`
	ReadingTime pgtype.Int4      `json:"reading_time"`
	Score       pgtype.Numeric   `json:"score"`
	Tags        []string         `json:"tags"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}
