// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountSearchContents(ctx context.Context, arg CountSearchContentsParams) (int64, error)
	DeleteContent(ctx context.Context, id pgtype.UUID) error
	GetContentByExternalID(ctx context.Context, arg GetContentByExternalIDParams) (GetContentByExternalIDRow, error)
	GetContentByID(ctx context.Context, id pgtype.UUID) (GetContentByIDRow, error)
	SearchContents(ctx context.Context, arg SearchContentsParams) ([]SearchContentsRow, error)
	UpsertContent(ctx context.Context, arg UpsertContentParams) (UpsertContentRow, error)
}

var _ Querier = (*Queries)(nil)
